# ~/.tmux.conf

# Character code
set -g default-terminal "tmux-256color"

# Disable startup message
set -g display-panes-time 1000
set -g display-time 1000

# Escape key
set -g prefix C-z
unbind C-b
bind C-z send-prefix

# Scroll setting
set -g history-limit 10000

# Mouse scroll
set -g mouse on

# Delete buffer (alternative screen)
setw -g alternate-screen on

# Color
set -g default-terminal "tmux-256color"

# Status line
set -g status-bg red
set -g status-fg white
setw -g window-status-current-bg blue
setw -g window-status-current-fg white
setw -g window-status-current-format "#I #W*"
setw -g window-status-format "#I #W"

# Hardstatus line
set -g status-left ""
set -g status-right "LoadAVG [#(uptime | awk '{print \$10, \$11, \$12}')]" # Adjust this as per your system

# Use default shell
set-option -g default-shell $SHELL

# Autodetach
set -g detach-on-destroy on
