[General]
borderColor=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\0\0\x7f\x7f\0\0)
borderSize=4
cursor=10
dotColor=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\0\0\0\0\0\0)
enableZoom=false
multiScreenOverlay=true
shadeColor=@Variant(\0\0\0\x43\x1\xff\xff\"\"\"\"\"\"\0\0)
shadeOpacity=0.6
showBorder=false
showCenterDot=false
showSpotShade=true
spotShape=spotshapes/Circle.qml
spotSize=30

[Device_046d_b503]
timer0enabled=false
timer0seconds=1
vibrationIntensity=200
vibrationLength=1

[Preset_preset%201]
Shape.Ngon\sides=3
Shape.Square\radius=20
Shape.Star\innerRadius=50
Shape.Star\points=5
borderColor=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\0\0\x7f\x7f\0\0)
borderOpacity=0.8
borderSize=4
cursor=10
dotColor=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\0\0\0\0\0\0)
dotOpacity=0.8
dotSize=5
enableZoom=false
multiScreenOverlay=true
shadeColor=@Variant(\0\0\0\x43\x1\xff\xff\"\"\"\"\"\"\0\0)
shadeOpacity=0.6
showBorder=false
showCenterDot=false
showSpotShade=true
spotRotation=0
spotShape=spotshapes/Circle.qml
spotSize=30
zoomFactor=2
